# Лабораторная работа № 0

1. С помощью массивов numpy создайте таблицу умножения.

In [ ]:
import numpy as np

numbers = np.arange(1, 11)
multiplication_table = np.outer(numbers, numbers)

print("Таблица умножения:")
print(multiplication_table)

Таблица умножения:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


2. Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число), и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов арифметической прогрессии.

In [10]:
def create_diagonal_matrix(N, first_element, difference):

    progression = np.arange(N) * difference + first_element
    diagonal_matrix = np.diag(progression)
    
    return diagonal_matrix

# Пример использования
N = 5
first_element = 2.5
difference = 1.5
result_matrix = create_diagonal_matrix(N, first_element, difference)
print(f"Количество членов арифметической прогрессии: {N}")
print(f"Первый элемент: {first_element}")
print(f"Разница: {difference}")
print("Результирующая матрица:")
print(result_matrix)


Количество членов арифметической прогрессии: 5
Первый элемент: 2.5
Разница: 1.5
Результирующая матрица:
[[2.5 0.  0.  0.  0. ]
 [0.  4.  0.  0.  0. ]
 [0.  0.  5.5 0.  0. ]
 [0.  0.  0.  7.  0. ]
 [0.  0.  0.  0.  8.5]]


3. Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.

In [29]:
A = np.arange(1, 26).reshape(5, 5)

# Извлекаем все нечетные элементы в плоский массив
odd_1 = A[0:5:2, 0:5:2].flatten()
odd_2 = A[1:4:2, 1:5:2].flatten()
res = np.hstack((odd_1, odd_2))
res.sort()

print("Матрица A:")
print(A)
print("\nНечетные элементы матрицы A:")
print(res)


Матрица A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Нечетные элементы матрицы A:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


4. Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [31]:
# Массив, заполненный нулями
array = np.zeros((5, 5), dtype=int)

array[0, :] = 1  # Первая строка
array[-1, :] = 1  # Последняя строка
array[:, 0] = 1  # Первый столбец
array[:, -1] = 1  # Последний столбец

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


5. Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.

In [ ]:
chess_matrix = np.zeros((5, 5), dtype=int)
chess_matrix[::2, ::2] = 5  # четные строки и столбцы
chess_matrix[1::2, 1::2] = 5  # нечетные строки и столбцы

print("Матрица в шахматном порядке:")
print(chess_matrix)

# Обратная матрица для треугольной матрицы
if det_triangular != 0:
    inverse_triangular = np.linalg.inv(triangular_matrix)
    print("\nОбратная треугольная матрица:")
    print(inverse_triangular)
else:
    print("\nОбратная матрица для треугольной матрицы не существует.")

# Обратная матрица для шахматной матрицы
if det_chess != 0:
    inverse_chess = np.linalg.inv(chess_matrix)
    print("\nОбратная шахматная матрица:")
    print(inverse_chess)
else:
    print("\nОбратная матрица для шахматной матрицы не существует.")

Матрица в шахматном порядке:
[[5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]]


In [33]:
triangular_matrix = np.triu(np.full((5, 5), 5), k=0)

print("\nТреугольная матрица:")
print(triangular_matrix)


Треугольная матрица:
[[5 5 5 5 5]
 [0 5 5 5 5]
 [0 0 5 5 5]
 [0 0 0 5 5]
 [0 0 0 0 5]]


In [34]:
det_chess = np.linalg.det(chess_matrix)

# Детерминант треугольной матрицы
det_triangular = np.linalg.det(triangular_matrix)

print("\nДетерминант шахматной матрицы:", det_chess)
print("Детерминант треугольной матрицы:", det_triangular)


Детерминант шахматной матрицы: 0.0
Детерминант треугольной матрицы: 3124.999999999999


In [35]:
# Обратная матрица для треугольной матрицы
if det_triangular != 0:
    inverse_triangular = np.linalg.inv(triangular_matrix)
    print("\nОбратная треугольная матрица:")
    print(inverse_triangular)
else:
    print("\nОбратная матрица для треугольной матрицы не существует.")

# Обратная матрица для шахматной матрицы
if det_chess != 0:
    inverse_chess = np.linalg.inv(chess_matrix)
    print("\nОбратная шахматная матрица:")
    print(inverse_chess)
else:
    print("\nОбратная матрица для шахматной матрицы не существует.")


Обратная треугольная матрица:
[[ 2.00000000e-01 -2.00000000e-01  1.11022302e-17 -6.16297582e-34
   3.42113883e-50]
 [ 0.00000000e+00  2.00000000e-01 -2.00000000e-01  1.11022302e-17
  -6.16297582e-34]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e-01 -2.00000000e-01
   1.11022302e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.00000000e-01
  -2.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.00000000e-01]]

Обратная матрица для шахматной матрицы не существует.


6. С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе.

In [ ]:
import pandas as pd

file_path = 'data.csv'
data = pd.read_csv(file_path)


      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2       

7. Выведите на экран несколько первых и несколько последний строк файла.

In [38]:
print("Первые 5 строк")
print(data.head())
print("Последние 5 строк")
print(data.tail())

Первые 5 строк
      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1

8. Выведите с помощью методов pandas основные количественные параметры датасета: количество строк и столбцов, тип данных каждого поля, количество значений в каждом столбце, шкала измерения каждого численного поля.

In [39]:
# 1. Количество строк и столбцов
num_rows, num_cols = data.shape
print(f"Количество строк: {num_rows}")
print(f"Количество столбцов: {num_cols}\n")

# 2. Тип данных каждого поля
print("Типы данных каждого столбца:")
print(data.dtypes, "\n")

# 3. Количество значений в каждом столбце
print("Количество значений в каждом столбце:")
print(data.count(), "\n")

# 4. Шкала измерения каждого численного поля
numerical_columns = data.select_dtypes(include=['int64', 'float64']).columns
print("Шкала измерения численных полей:")
for column in numerical_columns:
    min_value = data[column].min()
    max_value = data[column].max()
    print(f"{column}: от {min_value} до {max_value}")

Количество строк: 10000
Количество столбцов: 20

Типы данных каждого столбца:
Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object 

Количество значений в каждом столбце:
Id               10000
DistrictId       10000
Rooms            10000
Square           10000
LifeSquare        7887
KitchenSquare    10000
Floor            10000
HouseFloor       10000
HouseYear        10000
Ecology_1        10000
Ecology_2        10000
Ecology_3        10000
Social_1         10000
Social_2         10000
Social_3         10000
Healthcare_1      5202


9. Удалите из таблицы столбцы, содержащие идентификаторы, переименуйте все оставшиеся названия колонок на русском языке.

In [40]:
# 1. Удаление столбцов с идентификаторами
# Предположим, что столбцы с идентификаторами называются 'id', 'ID', 'Идентификатор' и т.д.
# Удаляем их с помощью метода drop()
columns_to_drop = [col for col in data.columns if 'id' in col.lower() or 'districtid' in col.lower()]
data = data.drop(columns=columns_to_drop)

# 2. Переименование оставшихся столбцов на русском языке
# словарь для переименования
rename_dict = {
    'Rooms': 'Количество комнат',
    'Square': 'Площадь',
    'LifeSquare': 'Жилая площадь',
	'KitchenSquare': 'Площадь кухни',
    'Floor': 'Этаж',
    'HouseFloor': 'Этажность дома',
    'HouseYear': 'Год постройки дома',
    'Ecology_1': 'Экология_1',
    'Ecology_2': 'Экология_2',
	'Ecology_3': 'Экология_3',
    'Social_1': 'Социальное_3',
    'Social_2': 'Социальное_3',
	'Social_3': 'Социальное_3',
    'Healthcare_1': 'Здоровье_2',
    'Helthcare_2': 'Здоровье_2',
	'Shops_1' : 'Магазин_1',
	'Shops_2' : 'Магазин_2',
	'Price' : 'Цена'
}
data = data.rename(columns=rename_dict)

print(data.head())

   Количество комнат     Площадь  Жилая площадь  Площадь кухни  Этаж  \
0                3.0  115.027311            NaN           10.0     4   
1                1.0   39.832524      23.169223            8.0     7   
2                3.0   78.342215      47.671972           10.0     2   
3                1.0   40.409907            NaN            1.0    10   
4                2.0   64.285067      38.562517            9.0    16   

   Этажность дома  Год постройки дома  Экология_1 Экология_2 Экология_3  \
0            10.0                2014    0.075424          B          B   
1             8.0                1966    0.118537          B          B   
2            17.0                1988    0.025609          B          B   
3            22.0                1977    0.007122          B          B   
4            16.0                1972    0.282798          B          B   

   Социальное_3  Социальное_3  Социальное_3  Здоровье_2  Здоровье_2  \
0            11          3097             0  

10. Выведите отдельно столбец, содержащий цену, по номеру и названию. Выведите первую, десятую и предпоследнюю строку таблицы по номеру и по индексу.

In [43]:
# 1. Вывод столбца с ценой по номеру и названию
price_by_name = data['Цена']  # По названию
price_by_index = data.iloc[:, 17]  # По индексу

print("Столбец с ценой (по названию):")
print(price_by_name)
print("\nСтолбец с ценой (по индексу):")
print(price_by_index)

# 2. Вывод первой, десятой и предпоследней строки по номеру и индексу
# По номеру строки
first_row_by_number = data.iloc[0]  # Первая строка
tenth_row_by_number = data.iloc[9]  # Десятая строка
second_last_row_by_number = data.iloc[-2]  # Предпоследняя строка

# По индексу
first_row_by_index = data.loc[data.index[0]]  # Первая строка
tenth_row_by_index = data.loc[data.index[9]]  # Десятая строка
second_last_row_by_index = data.loc[data.index[-2]]  # Предпоследняя строка

print("\nПервая строка (по номеру):")
print(first_row_by_number)
print("\nДесятая строка (по номеру):")
print(tenth_row_by_number)
print("\nПредпоследняя строка (по номеру):")
print(second_last_row_by_number)

print("\nПервая строка (по индексу):")
print(first_row_by_index)
print("\nДесятая строка (по индексу):")
print(tenth_row_by_index)
print("\nПредпоследняя строка (по индексу):")
print(second_last_row_by_index)

Столбец с ценой (по названию):
0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

Столбец с ценой (по индексу):
0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

Первая строка (по номеру):
Количество комнат               3.0
Площадь                  115.027311
Жилая площадь                   NaN
Площадь кухни                  10.0
Этаж                              4
Этажность дома                 10.0
Год постройки дома             2014
Экология_1                 0.075424
Экология_2                        B
Экология_3        

11. Выделите в отдельную таблицу последние десять строк. Уберите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи append. Заполните отсутствующие значения цены средним по таблице.

12. Выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к изначальной (выберите самый подходящий тип соединения).

13. Выведите таблицу, содержащую среднюю цену и количество квартир на каждом этаже из первоначального набора данных.

14. Сохраните получившуюся таблицу в файлы формата csv и xlsx. Прочитайте их и убедитесь, что данные отображаются корректно.

15. Создайте в Excel или другом табличном редакторе таблицу, содержащую несколько численных и текстовых полей. Прочитайте ее в программу при помощи pandas.

16. Дальнейшие задания производите используя изначальную версию датасета. Должны быть подписаны названия графиков, названия осей, указаны значения на осях. Оцениваться будет использование количества различных атрибутов при построении графиков и визуальная красота.

17. Постройте круговую диаграмму для признака Rooms, иллюстрирующую количество квартир в процентах в зависимости от количества комнат. Сделайте сектор с наибольшим числом квартир выдвинутым.

18. Постройте гистограмму по целевой переменной Price. Оцените визуально, по какой цене продаётся наибольшее количество квартир.

19. Постройте диаграммы рассеяния для признаков Rooms, Square, HouseFloor, HouseYear в зависимости от целевой переменной Price в одной области figure. Оцените визуально, есть ли среди них такие, на которых разброс точек близок к линейной функции.

20. Постройте ядерную оценку плотности целевой переменной Price. Оцените визуально, напоминает ли полученный график нормальное распределение. Постройте двумерную ядерную оценку плотности для целевой переменной Price и признака HouseFloor, затем оцените визуально на каких этажах и по какой цене продаётся основная масса квартир.

21. Постройте ящиковую диаграмму признака Square. Оцените визуально имеются ли выбросы, и, если да, то начиная с какого размера площади значение признака можно считать выбросом.

22. При помощи сетки графиков PairGrid визуализируйте попарные отношения признаков Rooms, Square, HouseFloor, HouseYear, Price следующим образом: на диагонали - гистограммы, под диагональю - ядерные оценки плотности, над диагональю - диаграммы рассеяния. По результатам визуализации сделайте выводы.

23. Постройте тепловую карту матрицы корреляции (df.corr()) признаков Rooms, Square, HouseFloor, HouseYear, Price. По ней определите, какие признаки являются зависимыми (у таких признаков коэффициент корреляции близок к единице).